backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit

  - name: "journal"
    label: "Journal"
    folder: "site/content/journal"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "authors", widget: "text" }
      - { label: "Location", name: "location", widget: "text" }
      - { label: "Teaser", name: "teaser", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "snapshots"
    label: "Snapshots"
    folder: "site/content/snapshots"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - name: author
        label: Author
        widget: relation
        collection: authors
        searchFields: [first_name, surname]
        valueField: first_name
      - { label: "Author", name: "authors", widget: "text" }
      - { label: "Teaser", name: "teaser", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About us"
        file: "site/content/about/_index.md"
        fields:
          - { label: Title, name: page_title, widget: "string" }
          - { label: Intro, name: page_intro, widget: "text" }

  - name: "settings"
    label: "Settings"
    files:
      - name: "general"
        label: "General"
        file: "site/data/settings.json"
        description: "General app settings"
        fields:
          - { label: "App Title", name: "app_title", widget: "string" }

      - name: "authors"
        label: "Authors"
        file: "site/data/authors.json"
        description: "Author descriptions"
        fields:
          - name: author
            label: Author
            widget: list
            fields:
              - { label: "First Name", name: "first_name", widget: "string" }
              - { label: "Surname", name: "surname", widget: "string" }
              - { label: "Bio", name: "bio", widget: "text" }
              - { label: "Avatar", name: "avatar", widget: "image" }

      - name: locations
        label: Locations
        file: "site/data/locations.json"
        description: "Location descriptions"
        fields:
          - name: location
            label: Location
            widget: list
            fields:
              - { label: "City", name: "city", widget: "string" }
              - { label: "Country", name: "country", widget: "string" }
