baseurl: "/"
languageCode: "en-us"
title: "Two New Natives"
relativeURLs: true

menu:
  main:
    - Name: "Journal"
      URL: "/journal/"
      weight: 1
      Identifier: "journal"
    - Name: "Snapshots"
      URL: "/snapshots/"
      weight: 2
      Identifier: "snapshots"
    - Name: "About Us"
      URL: "/about/"
      weight: 3
      Identifier: "about"
    - Name: "Galleries"
      URL: "/galleries/"
      weight: 4
      identifier: "galleries"

  footer:
    - Name: "Journal"
      URL: "/journal/"
      weight: 1
    - Name: "Snapshots"
      URL: "/snapshots/"
      weight: 2
    - Name: "About Us"
      URL: "/about/"
      weight: 3

taxonomies:
  tag: "tags"

params:
  social:
    - Name: "Facebook"
      ClassName: "fa-facebook"
      URL: "https://www.facebook.com/twonewnatives/"
    - Name: "Instagram"
      ClassName: "fa-instagram"
      URL: "https://www.instagram.com/twonewnatives/"
    - Name: "500px"
      ClassName: "fa-500px"
      URL: "https://500px.com/twonewnatives"
