baseurl: "/"
languageCode: "en-us"
title: "Two New Natives"

disqusShortname: "twonewnatives"

menu:
  main:
    - Name: "Journal"
      URL: "/journal/"
      weight: 1
    - Name: "Snapshots"
      URL: "/snapshots/"
      weight: 2
    - Name: "About Us"
      URL: "/about/"
      weight: 3

  footer:
    - Name: "Journal"
      URL: "/journal/"
      weight: 1
    - Name: "Snapshots"
      URL: "/snapshots/"
      weight: 2
    - Name: "About Us"
      URL: "/about/"
      weight: 3

taxonomies:
  tag: "tags"
  location: "locations"
  author: "authors"

params:
  social:
    - Name: "Facebook"
      ClassName: "fa-facebook"
      URL: "https://www.facebook.com/twonewnatives/"
    - Name: "Twitter"
      ClassName: "fa-twitter"
      URL: "https://twitter.com/twonewnatives"
    - Name: "Instagram"
      ClassName: "fa-instagram"
      URL: "https://www.instagram.com/twonewnatives/"
    - Name: "Facebook"
      ClassName: "fa-500px"
      URL: "https://500px.com/twonewnatives"
